[package]
name = "temperature"
version = "0.1.0"
authors = ["x0x0b <42596409+x0x0b@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
